const groups = [
  ['🌾','الجلوتين والقمح',['القمح','الشعير','الشوفان','الجاودار','السبيلت','الكاموت','خبز','معكرونة','برغل','سميد','فريكة','كسكس','مفتول','بسكويت القمح','بسكويت دايجستف','دايجستف','gluten','wheat','wheat biscuit','digestive biscuit','digestives','mcvities','oats']],
  ['🥛','كل الألبان',['حليب','جبنة','جبن','لبنة','لبن','زبادي','زبدة','قشدة','آيس كريم','كريمة','مصل الحليب','whey','milk','cheese','yogurt','dairy']],
  ['🌱','الصويا',['صويا','توفو','ليسيثين الصويا','e322','soy','tofu']],
  ['🍅','البندورة المعقودة',['معجون الطماطم','معجون البندورة','صلصة البندورة','صلصة الطماطم','كاتشاب','صلصة البيتزا','tomato paste','ketchup']],
  ['🫘','كل البقوليات',['حمص','عدس','فول','فاصولياء','فاصوليا','بازلاء','لوبيا','ترمس','فول سوداني','legume','lentil','chickpea','peanut']],
  ['🌰','كل المكسرات',['لوز','جوز','كاجو','بندق','فستق','صنوبر','ماكاداميا','بقان','almond','walnut','cashew','pistachio','nuts']],
  ['🌻','السمسم',['سمسم','طحينة','حلاوة','زيت السمسم','sesame','tahini']],
  ['🥚','البيض',['بيض','مايونيز','كاسترد','egg','mayonnaise','custard']],
  ['🍋','فواكه ممنوعة',['ليمون','فراولة','تفاح','مشمش','قمر الدين','كيوي','أناناس','lemon','strawberry','apple','apricot','kiwi','pineapple']],
  ['🥦','خضروات',['هليون','asparagus']],
  ['🦐','مأكولات بحرية قشرية',['جمبري','روبيان','محار','سلطعون','استاكوزا','سمك القد','بولوك','حبار','أبو سيف','سمك الفرخ','shrimp','prawn','crab','lobster','cod','pollock','squid','calamari','swordfish']],
  ['🐰','لحم الأرانب',['أرنب','ارنب','rabbit']],
  ['🍁','شراب القيقب',['شراب القيقب','شراب المابل','maple syrup']]
];
const $ = (id) => document.getElementById(id);
const foodList = $('foodList');
groups.forEach((g,i)=>{const article=document.createElement('article');article.className='food-group';article.innerHTML=`<h3>${g[0]} ${i+1}. ${g[1]}</h3><p>${g[2].join('، ')}</p>`;foodList.appendChild(article)});

const dayKey = new Date().toISOString().slice(0,10);
let usage;
try { usage=JSON.parse(localStorage.getItem('foodtracker-usage')) } catch { usage=null }
if(!usage || usage.day!==dayKey) usage={day:dayKey,image:10,text:10};
function saveUsage(){localStorage.setItem('foodtracker-usage',JSON.stringify(usage));$('imageCount').textContent=usage.image;$('textCount').textContent=usage.text}
saveUsage();

$('listToggle').addEventListener('click',()=>{const open=foodList.hidden;foodList.hidden=!open;$('listToggle').setAttribute('aria-expanded',String(open));$('arrow').textContent=open?'▲':'▼'});
let uploadedFile=null;
let visionModel=null;
let lastImageReading=null;
let imageAlreadyCounted=false;
function clearImage(){uploadedFile=null;lastImageReading=null;imageAlreadyCounted=false;$('previewWrap').hidden=true;$('previewImage').removeAttribute('src');$('cameraInput').value='';$('galleryInput').value=''}
$('removeImage').addEventListener('click',clearImage);
function imagePayload(image){const max=1600,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const url=canvas.toDataURL('image/jpeg',.84);return {mediaType:'image/jpeg',imageBase64:url.split(',')[1]}}
async function analyzeWithAI(image,userText){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),55000);try{const result=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...imagePayload(image),userText}),signal:controller.signal});if(!result.ok)return null;const data=await result.json();return ['prohibited','safe','uncertain'].includes(data.status)?data:null}catch{return null}finally{clearTimeout(timer)}}
function renderAIResult(data){if(data.kind==='not_food'){renderNonFood(data.productName||'شخص (ليس طعام)');return}const name=escapeHtml(data.productName||'المنتج المصوّر');const subtitle=data.subtitle?`<p class="product-name">${escapeHtml(data.subtitle)}</p>`:'';if(data.status==='uncertain'){renderUncertain(data.productName||'المنتج المصوّر',null);return}const prohibited=data.status==='prohibited';const detected=(data.detected||[]).map(item=>item.ingredient||item.group).filter(Boolean);const tags=[...new Set(detected)].map(item=>`<li>${escapeHtml(item)}</li>`).join('');const alternatives=(data.alternatives||[]).slice(0,3).map(item=>`<li>• ${escapeHtml(item)}</li>`).join('');$('result').innerHTML=`<section class="result-card ${prohibited?'danger':'safe'}"><div class="result-head"><span class="result-mark">${prohibited?'×':'✓'}</span><div><h3>${prohibited?'ممنوع — لا تأكلي':'لم نجد مكونات ممنوعة'}</h3><p class="product-name">${name}</p>${subtitle}</div></div>${prohibited?`<h4>مكونات ممنوعة تم اكتشافها</h4><ul class="detected-tags">${tags}</ul><h4>تنبيه: مصادر خفية محتملة</h4><p class="section-copy">${escapeHtml(data.hiddenWarning||'تحققي دائماً من الملصق ومن تحذير التلوث المتبادل.')}</p>`:`<h4>نتيجة الفحص</h4><p class="section-copy">${escapeHtml(data.evidence||'لم نكتشف مكونات من القائمة الممنوعة.')}</p>`}<h4>ملاحظات</h4><p class="section-copy">${escapeHtml(data.notes||'تحققي من الملصق لأن تركيبة المنتجات قد تتغير.')}</p>${alternatives?`<h4>بدائل آمنة مقترحة</h4><ul class="alternatives">${alternatives}</ul>`:''}</section>`}
function renderNonFood(name='شخص (ليس طعام)'){$('result').innerHTML=`<section class="result-card safe"><div class="result-head"><span class="result-mark">✓</span><div><h3>آمن للأكل</h3><p class="product-name">${escapeHtml(name)}</p></div></div><h4>ملاحظات</h4><p class="section-copy">الصورة تظهر شخصاً وليست طعاماً أو ملصق منتج غذائي. لا يمكن تحليل سلامة الطعام من هذه الصورة. يرجى تصوير ملصق المنتج أو الطعام المراد فحصه.</p></section>`}
async function receiveImage(file){if(!file)return;if(!file.type.startsWith('image/')){showMessage('يرجى اختيار ملف صورة صالح.');return}if(usage.image<=0){showMessage('انتهى رصيد فحص الصور لهذا اليوم. يعود الرصيد غداً.');return}uploadedFile=file;lastImageReading=null;imageAlreadyCounted=false;$('productName').value='';$('previewImage').src=URL.createObjectURL(file);$('previewName').textContent=file.name;$('previewWrap').hidden=false;try{await $('previewImage').decode()}catch{}$('checkButton').disabled=true;$('result').innerHTML='<p class="scan-progress">جاري تحليل المنتج بالذكاء الاصطناعي...</p>';const ingredients=$('ingredientsInput').value.trim();const aiResult=await analyzeWithAI($('previewImage'),ingredients);usage.image--;imageAlreadyCounted=true;saveUsage();if(aiResult){$('productName').value=aiResult.productName||'';renderAIResult(aiResult);$('checkButton').disabled=false;return}lastImageReading=await readImage();if(lastImageReading.labels.includes('person')){renderNonFood();$('checkButton').disabled=false;return}const recognizedName=inferProductName(lastImageReading);if(!$('productName').value.trim()&&recognizedName)$('productName').value=recognizedName;const name=$('productName').value.trim()||'المنتج المصوّر';const matches=analyze(`${name} ${ingredients} ${lastImageReading.ocrText}`);if(matches.length)renderResult(name,matches,lastImageReading);else if(!hasReliableEvidence(name,ingredients,lastImageReading))renderUncertain(name,lastImageReading);else renderResult(name,matches,lastImageReading);$('checkButton').disabled=false}
$('cameraInput').addEventListener('change',e=>receiveImage(e.target.files[0]));
$('galleryInput').addEventListener('change',e=>receiveImage(e.target.files[0]));
function showMessage(text){$('result').innerHTML=`<p class="result-note">${text}</p>`}
function normalize(s){return s.toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/[ًٌٍَُِّْـ]/g,'').trim()}
function editDistance(a,b){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let previous=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const saved=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(a[i-1]===b[j-1]?0:1));previous=saved}}return row[b.length]}
function analyze(value){const input=normalize(value);const tokens=input.split(/[^\u0600-\u06ffa-z0-9]+/).filter(Boolean);const matches=[];for(const g of groups){const ingredients=g[2].filter(item=>{const term=normalize(item);if(input.includes(term))return true;if(term.includes(' ')||term.length<4)return false;return tokens.some(token=>Math.abs(token.length-term.length)<=1&&editDistance(token,term)<=1)});if(ingredients.length)matches.push({group:g[1],ingredients})}return matches}
function escapeHtml(value){return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function knownProductName(reading){if(!reading||!reading.labels)return'';if(reading.labels.some(label=>label.toLowerCase().includes('mcvities')))return'بسكويت مكفتيز الهضمي بالقمح';return''}
function inferProductFromText(text){const value=normalize(text);const products=[['eggnog','شراب البيض بالحليب'],['low fat milk','حليب البقر قليل الدسم'],['whole milk','حليب البقر كامل الدسم'],['milk','حليب البقر'],['wheat biscuit','بسكويت القمح'],['digestive','بسكويت هضمي'],['yogurt','زبادي'],['cheese','جبنة'],['ice cream','آيس كريم'],['mayonnaise','مايونيز'],['tahini','طحينة'],['tofu','توفو'],['soy milk','حليب الصويا'],['almond milk','حليب اللوز'],['peanut butter','زبدة الفول السوداني'],['bread','خبز'],['pasta','معكرونة'],['shrimp','روبيان'],['crab','سلطعون'],['lobster','استاكوزا'],['lemon','ليمون'],['strawberry','فراولة'],['apple','تفاح'],['pineapple','أناناس']];const match=products.find(([term])=>value.includes(term));return match?match[1]:''}
function inferProductName(reading){if(!reading)return'';const known=knownProductName(reading);if(known)return known;const fromText=inferProductFromText(reading.ocrText);if(fromText)return fromText;const foodLabels=friendlyLabels(reading.labels);return foodLabels.length?foodLabels[0]:'المنتج المصوّر'}
async function readImage(){
  const image=$('previewImage');
  const findings=[];
  try{if('FaceDetector' in window){const faces=await new FaceDetector({fastMode:true,maxDetectedFaces:3}).detect(image);if(faces.length)findings.push('person')}}catch(error){console.warn('Face detection unavailable',error)}
  let ocrText='';
  let ocrConfidence=0;
  try{
    $('result').innerHTML='<p class="scan-progress">جاري قراءة النص من الصورة...</p>';
    const worker=await Tesseract.createWorker('eng+ara',1,{workerPath:'vendor/tesseract/worker.min.js',corePath:'vendor/tesseract/core',langPath:'vendor/tesseract/lang',gzip:true});
    await worker.setParameters({tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'});
    const prepared=prepareProductImage(image);
    const output=await worker.recognize(prepared);
    ocrConfidence=Number(output.data.confidence||0);
    ocrText=cleanOcrText(output.data.text||'',ocrConfidence);
    if(!analyze(ocrText).length){const fullOutput=await worker.recognize(prepareFullImage(image));const fullConfidence=Number(fullOutput.data.confidence||0);const fullText=cleanOcrText(fullOutput.data.text||'',fullConfidence);if(fullText){ocrText=`${ocrText} ${fullText}`.trim();ocrConfidence=Math.max(ocrConfidence,fullConfidence)}}
    await worker.terminate();
  }catch(error){console.warn('OCR unavailable',error)}
  try{
    $('result').innerHTML='<p class="scan-progress">جاري التعرّف على الطعام في الصورة...</p>';
    if(!visionModel)visionModel=await mobilenet.load();
    const predictions=await visionModel.classify(image,5);
    const personWords=['person','groom','suit','windsor tie','academic gown','jersey'];
    if(predictions.some(item=>item.probability>=.18&&personWords.some(word=>item.className.toLowerCase().includes(word))))findings.push('person');
  }catch(error){console.warn('Image classification unavailable',error)}
  return {ocrText,ocrConfidence,labels:[...new Set(findings)]};
}
function prepareProductImage(image){const source=document.createElement('canvas');source.width=image.naturalWidth;source.height=image.naturalHeight;const context=source.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0);const pixels=context.getImageData(0,0,source.width,source.height).data;let minX=source.width,minY=source.height,maxX=0,maxY=0,count=0;for(let y=0;y<source.height;y+=3){for(let x=0;x<source.width;x+=3){const index=(y*source.width+x)*4;const r=pixels[index],g=pixels[index+1],b=pixels[index+2];const high=Math.max(r,g,b),low=Math.min(r,g,b);if(high>70&&high-low>55){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);count++}}}if(count<80){minX=0;minY=0;maxX=source.width;maxY=source.height}const padX=Math.round((maxX-minX)*.08),padY=Math.round((maxY-minY)*.12);minX=Math.max(0,minX-padX);minY=Math.max(0,minY-padY);maxX=Math.min(source.width,maxX+padX);maxY=Math.min(source.height,maxY+padY);const width=Math.max(1,maxX-minX),height=Math.max(1,maxY-minY);const scale=Math.min(3,Math.max(1.6,1400/width));const output=document.createElement('canvas');output.width=Math.round(width*scale);output.height=Math.round(height*scale);const out=output.getContext('2d');out.imageSmoothingEnabled=true;out.imageSmoothingQuality='high';out.drawImage(source,minX,minY,width,height,0,0,output.width,output.height);return output}
function prepareFullImage(image){const scale=Math.min(3,Math.max(1.5,1500/image.naturalWidth));const canvas=document.createElement('canvas');canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);const context=canvas.getContext('2d');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(image,0,0,canvas.width,canvas.height);return canvas}
function cleanOcrText(text,confidence){if(confidence<38)return'';const words=text.replace(/[^\u0600-\u06FFa-zA-Z0-9%.,()\-\s]/g,' ').split(/\s+/).filter(word=>word.length>=2||/^[0-9]+%?$/.test(word));const meaningful=words.filter(word=>/[\u0600-\u06FFa-zA-Z]{2}/.test(word)||/^[0-9]+%?$/.test(word));return meaningful.join(' ').slice(0,360)}
function friendlyLabels(labels){const map={fig:'تين',milk:'حليب',yogurt:'زبادي',cheese:'جبنة',bread:'خبز',banana:'موز',orange:'برتقال',lemon:'ليمون',pineapple:'أناناس',strawberry:'فراولة',apple:'تفاح',broccoli:'بروكلي',cucumber:'خيار',mushroom:'فطر',pizza:'بيتزا',icecream:'آيس كريم'};return labels.map(label=>{const first=label.split(',')[0].trim();const key=Object.keys(map).find(item=>first.toLowerCase().includes(item));return key?map[key]:first}).filter(Boolean)}
function hasRecognizableFoodText(text){const known=['rice','chicken','beef','banana','orange','water','juice','coffee','tea','coconut','potato','corn','soda','cola','pepsi','fanta','sprite','7up','soft drink','بسكويت','ارز','أرز','دجاج','لحم','موز','برتقال','ماء','عصير','مشروب غازي','بطاطا','ذرة'];return analyze(text).length>0||known.some(term=>normalize(text).includes(normalize(term)))}
function hasReliableEvidence(name,ingredients,reading){return Boolean(ingredients.trim()||(reading&&reading.ocrText&&reading.ocrConfidence>=38&&hasRecognizableFoodText(reading.ocrText)))}
function suggestions(matches){const names=matches.map(m=>m.group).join(' ');if(names.includes('الألبان'))return['حليب جوز الهند','حليب الأرز','حليب الشوفان الخالي من الجلوتين','منتج نباتي معتمد خالٍ من الألبان'];if(names.includes('الجلوتين'))return['بسكويت مصنوع من دقيق الأرز','منتج شوفان معتمد خالٍ من الجلوتين','كراكرز من دقيق الذرة أو الحنطة السوداء','بسكويت من دقيق جوز الهند'];if(names.includes('البيض'))return['بديل البيض النباتي','بذور الكتان المطحونة مع الماء','مهروس الموز للخبز','صلصة خالية من المايونيز'];return['منتج بسيط المكونات وخالٍ من العناصر المذكورة','بديل منزلي بمكونات موثوقة','منتج يحمل ملصقاً واضحاً وخالياً من مسببات الحساسية','طعام طازج غير مصنّع من القائمة الآمنة']}
function displayIngredient(item){const translations={'القمح':'قمح',wheat:'قمح','wheat biscuit':'بسكويت القمح',digestives:'بسكويت هضمي',mcvities:'مكفتيز',gluten:'جلوتين',milk:'حليب',cheese:'جبنة',yogurt:'زبادي',egg:'بيض',sesame:'سمسم',soy:'صويا',peanut:'فول سوداني',almond:'لوز'};return translations[item.toLowerCase()]||item}
function canonicalDetectedTags(matches){const labels={'الجلوتين والقمح':'قمح وجلوتين','كل الألبان':'حليب ومشتقات ألبان','الصويا':'صويا','البندورة المعقودة':'معجون أو صلصة طماطم','كل البقوليات':'بقوليات','كل المكسرات':'مكسرات','السمسم':'سمسم','البيض':'بيض','فواكه ممنوعة':'فاكهة ممنوعة','خضروات':'هليون','مأكولات بحرية قشرية':'مأكولات بحرية ممنوعة','لحم الأرانب':'لحم أرنب','شراب القيقب':'شراب القيقب'};return [...new Set(matches.map(match=>labels[match.group]||match.group))]}
function hiddenWarning(matches){const names=matches.map(m=>m.group).join(' ');if(names.includes('الجلوتين'))return'المنتج قد يحتوي على دقيق القمح أو الشعير أو منكهات ومواد رابطة مشتقة من الجلوتين. تحققي من عبارة «خالٍ من الجلوتين» ومن تحذير التلوث المتبادل.';if(names.includes('الألبان'))return'قد تظهر مشتقات الحليب بأسماء مثل مصل الحليب، الكازين، الزبدة أو مسحوق الحليب. كل مشتقات الألبان تدخل ضمن هذه المجموعة.';if(names.includes('الصويا'))return'قد تكون الصويا مخفية تحت أسماء مثل ليسيثين الصويا E322 أو البروتين النباتي المتحلل.';return'قد توجد مصادر خفية أو آثار من هذه المكونات. افحصي عبارات «قد يحتوي على» و«مصنّع في منشأة تستخدم» على العبوة.'}
function imageReadingBlock(reading){if(!reading)return'';const known=knownProductName(reading);if(known)return `<div class="image-reading"><strong>ما تمّت قراءته من الصورة</strong><p>تم التعرف على المنتج: ${escapeHtml(known)}</p></div>`;const labels=friendlyLabels(reading.labels);const visible=[labels.length?`تم التعرف بصرياً على: ${labels.join('، ')}`:'',reading.ocrText?`النص المقروء: ${reading.ocrText}`:''].filter(Boolean);return `<div class="image-reading"><strong>ما تمّت قراءته من الصورة</strong><p>${visible.length?visible.map(escapeHtml).join('<br>'):'الصورة غير واضحة بما يكفي لقراءة تفاصيل موثوقة. صوّري الملصق مباشرة بإضاءة جيدة أو اكتبي المكونات يدوياً.'}</p></div>`}
function renderUncertain(name,reading){$('result').innerHTML=`<section class="result-card uncertain"><div class="result-head"><span class="result-mark">!</span><div><h3>لا يمكن تأكيد الأمان</h3><p class="product-name">${escapeHtml(name)}</p></div></div>${imageReadingBlock(reading)}<h4>النتيجة</h4><p class="section-copy">لم نحصل على معلومات واضحة وكافية من الصورة. لذلك لن نعتبر المنتج آمناً.</p><h4>ما الذي يجب فعله؟</h4><div class="result-note">صوّري واجهة المنتج وقائمة المكونات بوضوح، أو اكتبي اسم المنتج والمكونات يدوياً ثم أعيدي الفحص.</div></section>`}
function renderResult(name,matches,reading){const inferred=reading?inferProductName(reading):name;const safeName=escapeHtml(inferred&&inferred!=='المنتج المصوّر'?inferred:name);if(matches.length){const tags=canonicalDetectedTags(matches).map(item=>`<li>${escapeHtml(item)}</li>`).join('');const alternatives=suggestions(matches).slice(0,3).map(item=>`<li>• ${item}</li>`).join('');$('result').innerHTML=`<section class="result-card danger"><div class="result-head"><span class="result-mark">×</span><div><h3>ممنوع — لا تأكلي</h3><p class="product-name">${safeName}</p></div></div><h4>مكونات ممنوعة تم اكتشافها</h4><ul class="detected-tags">${tags}</ul><h4>تنبيه: مصادر خفية محتملة</h4><p class="section-copy">${escapeHtml(hiddenWarning(matches))}</p><h4>ملاحظات</h4><p class="section-copy">هذا المنتج ممنوع تماماً لأنه يحتوي على مكونات من المجموعات الممنوعة. تجنبيه كلياً حتى لو كانت الكمية قليلة، وتحققي دائماً من الملصق لأن التركيبات قد تتغير.</p><h4>بدائل آمنة مقترحة</h4><ul class="alternatives">${alternatives}</ul></section>`}else{$('result').innerHTML=`<section class="result-card safe"><div class="result-head"><span class="result-mark">✓</span><div><h3>لم نجد مكونات ممنوعة</h3><p class="product-name">${safeName}</p></div></div><h4>نتيجة الفحص</h4><p class="section-copy">لم نكتشف أياً من المجموعات الممنوعة في الاسم أو المكونات أو النص الواضح المقروء من الصورة.</p><h4>ملاحظات</h4><div class="result-note">يبدو مناسباً بحسب البيانات المتاحة. افحصي العبوة كاملة وتأكدي من التحذيرات ومخاطر التلوث المتبادل قبل تناوله.</div></section>`}}
$('foodForm').addEventListener('submit',async e=>{e.preventDefault();const ingredients=$('ingredientsInput').value.trim();if(!ingredients&&!uploadedFile){showMessage('اكتبي اسم الطعام أو المكونات، أو ارفعي صورة لإجراء الفحص.');return}let name=$('productName').value.trim()||ingredients.slice(0,80)||'المنتج المصوّر';const mode=uploadedFile?'image':'text';if(!imageAlreadyCounted&&usage[mode]<=0){showMessage('انتهى رصيد الفحص التجريبي لهذا اليوم. يعود الرصيد غداً.');return}$('checkButton').disabled=true;let reading=lastImageReading;if(uploadedFile&&!reading)reading=await readImage();else if(!uploadedFile)$('result').innerHTML='<p class="loading">جاري فحص المنتج والمكونات...</p>';if(reading&&reading.labels.includes('person')){renderNonFood();$('checkButton').disabled=false;return}if(reading&&!$('productName').value.trim()){const inferred=inferProductName(reading);if(inferred)name=inferred}if(!imageAlreadyCounted){usage[mode]--;saveUsage()}const imageText=reading?reading.ocrText:'';const matches=analyze(`${name} ${ingredients} ${imageText}`);if(matches.length)renderResult(name,matches,reading);else if(uploadedFile&&!hasReliableEvidence(name,ingredients,reading))renderUncertain(name,reading);else renderResult(name,matches,reading);$('checkButton').disabled=false});
